# ラベルの定義
labels:
  - name: "CS"
    description: "カスタマーサクセス"
    color: "d4c5f9"
  - name: "DEV"
    description: "開発"
    color: "bfe5bf"
  - name: "Document"
    description: "ドキュメント"
    color: "bfe5bf"
  - name: "Release"
    description: "リリース"
    color: "bfdadc"
  - name: "Hotfix"
    description: "不具合修正"
    color: "fef2c0"

# 展開対象のリポジトリと設定するラベル
repos:
  - name: ksh-fthr/test_workflow
    # labels で定義したラベルから設定する
    labels:
      - CS
      - DEV
      - Document
      - Release
      - Hotfix

  - name: ksh-fthr/FileUtilityTools
    # labels で定義したラベルから設定する
    labels:
      - CS
      - DEV
      - Document
      - Release
      - Hotfix
