name: Dry Run
on:
  label:
    types: [created]
jobs:
  github-labeler:
    name: dry-run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: github-labeler
        uses: ./.github/actions/action.yml
        with:
          dry_run: true
